name: Build Flet Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet CLI
        run: pip install flet-cli

      - name: Build Android APK
        run: flet publish android --no-open
